### ISSUE TITLE
Go-ndn ping

### ISSUE THREAD

**Issue by qhsong** [go-ndn/ndn#1]
Hello,
I write a go-ndn ping program using go-ndn, [go-ndn-ping](github.com/qhsong/go-ndn-ping), It has been tested in mininet network,can you give some advice about it?

**Comment by taylorchu** [comment]
The stats is empty. 

`49 Interests transmmitted, 49 Data received, 0.0% packet loss, time 48.408288947s
rtt min/avg/max/mdev = 0.000/0.000/0.000/0.000 ms`

Also it is better if no verifier is used because verification could affect timing.

**Comment by qhsong** [comment]
ok, I will fix it.Thanks for your advice.
